# -*- coding: utf-8 -*-
"""etl-data-pipeline-2500592021.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p4X1peraiJ6TVJ2-Faux_PO9Z3T4zUnm
"""

#CONEXION

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_data_pipeline_2500592021_user:va5Onu074qqAOmWJJAbDfgmA7KS1q0I7@dpg-d6vhohaa214c738ab6mg-a.oregon-postgres.render.com/etl_data_pipeline_2500592021"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

import pandas as pd

url = "https://raw.githubusercontent.com/BBulnes20/etl-data-pipeline-2500592021/refs/heads/main/data/raw/E_bodegas.csv"

df_bodegas = pd.read_csv(url)

df_bodegas.head()

import pandas as pd

url = "https://raw.githubusercontent.com/BBulnes20/etl-data-pipeline-2500592021/refs/heads/main/data/raw/E_inventario.csv"

df_inventario = pd.read_csv(url)

df_inventario.head()

import pandas as pd

url = "https://raw.githubusercontent.com/BBulnes20/etl-data-pipeline-2500592021/refs/heads/main/data/raw/E_movimientos.csv"

df_movimientos = pd.read_csv(url)

df_movimientos.head()

#EXPLORACION DE DATOS

df_movimientos.shape
df_movimientos.columns
df_movimientos.info()
df_movimientos.isnull().sum()

#LIMPIEZA DE DATOS BODEGAS

bodegas = df_bodegas.copy()

bodegas.columns = bodegas.columns.str.strip().str.lower()

for col in bodegas.select_dtypes(include='object').columns:
    bodegas[col] = bodegas[col].astype(str).str.strip()

bodegas = bodegas.replace(r'^\s*$', pd.NA, regex=True)

# Clean 'capacidad_m2' column: remove ' m2' and convert to numeric
bodegas['capacidad_m2'] = bodegas['capacidad_m2'].astype(str).str.replace(' m2', '', regex=False)
bodegas['capacidad_m2'] = pd.to_numeric(bodegas['capacidad_m2'], errors='coerce')

bodegas = bodegas.drop_duplicates()

print("DataFrame 'bodegas' después de la limpieza:")
print(bodegas.head())
print("Información del DataFrame 'bodegas' después de la limpieza:")
bodegas.info()
print("Valores nulos en 'bodegas' después de la limpieza:")
print(bodegas.isnull().sum())

#LIMPIEZA DE DATOS DE INVENTARIO

inventario = df_inventario.copy()

inventario.columns = inventario.columns.str.strip().str.lower()

for col in inventario.select_dtypes(include='object').columns:
    inventario[col] = inventario[col].astype(str).str.strip()

inventario = inventario.replace(r'^\s*$', pd.NA, regex=True)

# Clean 'costo_unitario' column: remove '$' and convert to numeric
inventario['costo_unitario'] = inventario['costo_unitario'].astype(str).str.replace('$', '', regex=False)
inventario['costo_unitario'] = pd.to_numeric(inventario['costo_unitario'], errors='coerce')

# Clean 'cantidad' column: remove non-numeric characters and convert to numeric
inventario['cantidad'] = inventario['cantidad'].astype(str).str.replace(r'[^0-9.]', '', regex=True)
inventario['cantidad'] = pd.to_numeric(inventario['cantidad'], errors='coerce')

inventario = inventario.drop_duplicates()

print("DataFrame 'inventario' después de la limpieza:")
print(inventario.head())
print("Información del DataFrame 'inventario' después de la limpieza:")
inventario.info()
print("Valores nulos en 'inventario' después de la limpieza:")
print(inventario.isnull().sum())

#LIMPIEZA DE DATOS MOVIMIENTOS



movimientos = df_movimientos.copy()

movimientos.columns = movimientos.columns.str.strip().str.lower()

for col in movimientos.select_dtypes(include='object').columns:
    movimientos[col] = movimientos[col].astype(str).str.strip()

movimientos = movimientos.replace(r'^\s*$', pd.NA, regex=True)

# Clean 'cantidad_movimiento' column: remove non-numeric characters and convert to numeric
movimientos['cantidad_movimiento'] = movimientos['cantidad_movimiento'].astype(str).str.replace(r'[^0-9.]', '', regex=True)
movimientos['cantidad_movimiento'] = pd.to_numeric(movimientos['cantidad_movimiento'], errors='coerce')

# Convert 'fecha' to datetime
movimientos['fecha'] = pd.to_datetime(movimientos['fecha'], errors='coerce')

movimientos = movimientos.drop_duplicates()

print("DataFrame 'movimientos' después de la limpieza:")
print(movimientos.head())
print("Información del DataFrame 'movimientos' después de la limpieza:")
movimientos.info()
print("Valores nulos en 'movimientos' después de la limpieza:")
print(movimientos.isnull().sum())

#SEPARAR DATOS EN VALIDOS Y RECHAZADOS BODEGAS

bodegas_validas = bodegas[bodegas['capacidad_m2'].notna()].copy()
bodegas_rechazadas = bodegas[bodegas['capacidad_m2'].isna()].copy()

print("DataFrame 'bodegas_validas' (validas):")
print(bodegas_validas.head())
print("Número de filas válidas:", len(bodegas_validas))

print("\nDataFrame 'bodegas_rechazadas' (rechazadas):")
print(bodegas_rechazadas.head())
print("Número de filas rechazadas:", len(bodegas_rechazadas))

if bodegas_rechazadas.empty:
    print("\n¡Excelente! No se encontraron filas rechazadas en el DataFrame 'bodegas' según la validación de 'capacidad_m2'.")

#SEPARAR DATOS EN VALIDOS Y RECHAZADOS INVENTARIO

inventario_validos = inventario[inventario['cantidad'].notna() & inventario['costo_unitario'].notna()].copy()
inventario_rechazados = inventario[inventario['cantidad'].isna() | inventario['costo_unitario'].isna()].copy()

print("DataFrame 'inventario_validos' (validos):")
print(inventario_validos.head())
print("Número de filas válidas:", len(inventario_validos))

print("\nDataFrame 'inventario_rechazados' (rechazadas):")
print(inventario_rechazados.head())
print("Número de filas rechazadas:", len(inventario_rechazados))

if inventario_rechazados.empty:
    print("\n¡Excelente! No se encontraron filas rechazadas en el DataFrame 'inventario'.")
else:
    print("\nSe encontraron filas rechazadas en el DataFrame 'inventario' basadas en valores nulos en 'cantidad' o 'costo_unitario'.")

#SEPARAR DATOS EN VALIDOS Y RECHAZADOS MOVIMIENTOS

movimientos_validos = movimientos[movimientos['fecha'].notna() & movimientos['cantidad_movimiento'].notna()].copy()
movimientos_rechazados = movimientos[movimientos['fecha'].isna() | movimientos['cantidad_movimiento'].isna()].copy()

print("DataFrame 'movimientos_validos' (validos):")
print(movimientos_validos.head())
print("Número de filas válidas:", len(movimientos_validos))

print("\nDataFrame 'movimientos_rechazados' (rechazadas):")
print(movimientos_rechazados.head())
print("Número de filas rechazadas:", len(movimientos_rechazados))

if movimientos_rechazados.empty:
    print("\n¡Excelente! No se encontraron filas rechazadas en el DataFrame 'movimientos'.")
else:
    print("\nSe encontraron filas rechazadas en el DataFrame 'movimientos' basadas en valores nulos en 'fecha' o 'cantidad_movimiento'.")

#EXPORTAR ARCHIVOS

bodegas_validas.to_csv("bodegas_curated.csv", index = False)

bodegas_rechazadas.to_csv("bodegas_rejects.csv", index = False)

inventario_validos.to_csv("inventario_curated.csv", index = False)

inventario_rechazados.to_csv("inventario_rejects.csv", index = False)

movimientos_validos.to_csv("movimientos_curated.csv", index = False)

movimientos_rechazados.to_csv("movimientos_rejects.csv", index = False)

#CONECTAR CON POSTGRESQL

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_data_pipeline_2500592021_user:va5Onu074qqAOmWJJAbDfgmA7KS1q0I7@dpg-d6vhohaa214c738ab6mg-a.oregon-postgres.render.com/etl_data_pipeline_2500592021"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

#CARGAR DATOS

bodegas_validas.to_sql(
    'bodegas_curated',
    engine,
    if_exists='append',
    index=False
)

bodegas_rechazadas.to_sql(
    'bodegas_rejects',
    engine,
    if_exists='append',
    index=False
)

inventario_validos.to_sql(
    'inventario_curated',
    engine,
    if_exists='append',
    index=False
)

inventario_rechazados.to_sql(
    'inventario_rejects',
    engine,
    if_exists='append',
    index=False
)

movimientos_validos.to_sql(
    'movimientos_curated',
    engine,
    if_exists='append',
    index=False
)

movimientos_rechazados.to_sql(
    'movimientos_rejects',
    engine,
    if_exists='append',
    index=False
)

#VALIDAR CARGA

pd.read_sql(
    "SELECT * FROM bodegas_curated LIMIT 10",
    engine
)

pd.read_sql(
    "SELECT * FROM inventario_curated LIMIT 10",
    engine
)

pd.read_sql(
    "SELECT * FROM movimientos_curated LIMIT 10",
    engine
)